# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    import seaborn as sns
    penguins = sns.load_dataset("penguins")

    # ========================================================================

    from shiny.express import render, ui
    ui.input_select("x",
                    "Variable:",
                    choices=["bill_length_mm", "bill_depth_mm"])
    ui.input_select("dist", 
                    "Distribution:", 
                    choices=["hist", "kde"])
    ui.input_checkbox("rug",
                      "Show rug marks", 
                      value = False)

    # ========================================================================

    @render.plot
    def displot():
        sns.displot(
            data=penguins, 
            hue="species",
            multiple="stack",
            x=input.x(),
            rug=input.rug(),
            kind=input.dist())

    # ========================================================================



    return None


_static_assets = ["dashboard_files","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\tippy.css","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css","qmd-dashboard\\dashboard_files\\libs\\bootstrap\\bootstrap-icons.css","qmd-dashboard\\dashboard_files\\libs\\bootstrap\\bootstrap-f547ca9f9d437787137f2e2308b6cde4.min.css","qmd-dashboard\\dashboard_files\\libs\\bootstrap\\bootstrap-dark-f547ca9f9d437787137f2e2308b6cde4.min.css","qmd-dashboard\\dashboard_files\\libs\\clipboard\\clipboard.min.js","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\quarto.js","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\tabsets\\tabsets.js","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\popper.min.js","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\tippy.umd.min.js","qmd-dashboard\\dashboard_files\\libs\\quarto-html\\anchor.min.js","qmd-dashboard\\dashboard_files\\libs\\bootstrap\\bootstrap.min.js","qmd-dashboard\\dashboard_files\\libs\\quarto-dashboard\\quarto-dashboard.js","qmd-dashboard\\dashboard_files\\libs\\quarto-dashboard\\stickythead.js","qmd-dashboard\\dashboard_files\\libs\\quarto-dashboard\\web-components.js","qmd-dashboard\\dashboard_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "dashboard.html",
    server,
    static_assets=_static_assets,
)
